site_name: Paysage Documentation
pages:
    - Home: index.md
    - Overview: overview.md
    - Batch: batch.md
    - Layers: layers.md
    - Hidden: hidden.md
    - Initialize Hidden: init_hidden.md
    - Model Fitting: fit.md
    - Optimizers: optimizers.md
    - Metrics: metrics.md
    - Constraints: constraints.md
    - Penalties: penalties.md
    - Deep: deep.md
    - Initialize Deep: init_deep.md
    - Recurrent: recurrent.md
    - Initialize Recurrent: init_recurrent.md
    - Backends: backends.md
theme: readthedocs

